### ISSUE TITLE
Layout problem on iPad

### ISSUE THREAD

**Issue by LeePower** [messier219/mneme#2]
Hi, first of all, thank you for the great work! I really like this theme!
However, when I view it on iPad or mobile phone, the layout is not correct as the cover images are oversizes, please help to fix this problem, thanks!

**Comment by messier219** [comment]
Sorry, I'm late. I checked this problem.
The cause of this problem is mobile browsers do not support a particular CSS. (background-attachment: fixed)
So I had to change the cover output structure.
For a mobile browser cover image is printed at the top.

Fixed version is v0.3.2 - https://github.com/messier219/mneme/releases/tag/0.3.2

Thank you for your attention.
